In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.ones(2,2)

In [ ]:
# tensor와 메모리 공유 
np_array = tensor.numpy()  # 참조(같은 메모리 주소 가리킴)
np_array

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
# tensor 복사본
np_array2 = np.array(tensor) # 새 메모리 할당
np_array2

/var/folders/gr/1kzgqp010_q1nm5qxbm9qy_r0000gn/T/ipykernel_8936/2454444564.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  np_array2 = np.array(tensor)


array([[1., 1.],
       [1., 1.]], dtype=float32)

In [5]:
tensor[0,0] = -1

In [6]:
print(f'numpy() result\n{np_array}\n')

print(f'np.array() result\n{np_array2}')

numpy() result
[[-1.  1.]
 [ 1.  1.]]

np.array() result
[[1. 1.]
 [1. 1.]]
