In [2]:
import torch

In [3]:
data_list = [1, 2]

tensor = torch.tensor(data_list)
tensor

tensor([1, 2])

In [4]:
type(tensor)

torch.Tensor

In [5]:
print(f'data type: {tensor.dtype}')

data type: torch.int64


In [7]:
print(f'number of dimensions: {tensor.ndim}')

number of dimensions: 1


In [8]:
print(f'shape: {tensor.shape}')

shape: torch.Size([2])


In [9]:
print(f'size: {tensor.size()}')

size: torch.Size([2])


In [ ]:
import numpy as np

data_np = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

# numpy 배열을 torch 텐서로 변환
tensor_np = torch.tensor(data_np)
tensor_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
# numpy 배열을 공유함. 따라서 numpy 배열을 변경하면 torch 텐서도 변경됨
tensor_from_numpy = torch.from_numpy(data_np)
tensor_from_numpy

tensor([[1, 2],
        [3, 4]])

In [15]:
data_np[0, 0] = -1

print(f'torch.tensor() result\n{tensor_np}\n')

print(f'torch.from_numpy() result\n{tensor_from_numpy}')

torch.tensor() result
tensor([[1, 2],
        [3, 4]])

torch.from_numpy() result
tensor([[-1,  2],
        [ 3,  4]])


In [17]:
print(tensor.dtype)

print(tensor_np.dtype)

# 기본은 int형임


torch.int64
torch.int64


In [19]:
tensor = torch.tensor([1, 1.5])
tensor.dtype

torch.float32

In [20]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor.dtype

torch.float32