source .venv/bin/activate


In [1]:
import torch

In [2]:
data_list = [1, 2]

tensor = torch.tensor(data_list)
tensor

tensor([1, 2])

In [3]:
type(tensor)

torch.Tensor

In [4]:
print(f'data type: {tensor.dtype}')

data type: torch.int64


In [5]:
print(f'number of dimensions: {tensor.ndim}')

number of dimensions: 1


In [6]:
print(f'shape: {tensor.shape}')

shape: torch.Size([2])


In [7]:
print(f'size: {tensor.size()}')

size: torch.Size([2])


In [8]:
import numpy as np

data_np = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

# numpy 배열을 torch 텐서로 변환
tensor_np = torch.tensor(data_np)
tensor_np

tensor([[1, 2],
        [3, 4]])

In [9]:
# numpy 배열을 공유함. 따라서 numpy 배열을 변경하면 torch 텐서도 변경됨
tensor_from_numpy = torch.from_numpy(data_np)
tensor_from_numpy

tensor([[1, 2],
        [3, 4]])

In [10]:
data_np[0, 0] = -1

print(f'torch.tensor() result\n{tensor_np}\n')

print(f'torch.from_numpy() result\n{tensor_from_numpy}')

torch.tensor() result
tensor([[1, 2],
        [3, 4]])

torch.from_numpy() result
tensor([[-1,  2],
        [ 3,  4]])


In [11]:
print(tensor.dtype)

print(tensor_np.dtype)

# 기본은 int형임


torch.int64
torch.int64


In [12]:
tensor = torch.tensor([1, 1.5])
tensor.dtype

torch.float32

In [13]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor.dtype

torch.float32

In [14]:
torch.rand(2, 3)

tensor([[0.4324, 0.9517, 0.0902],
        [0.2789, 0.0665, 0.6792]])

In [15]:
# 리스트
torch.rand([2, 3])

tensor([[0.2568, 0.8984, 0.7366],
        [0.4144, 0.2340, 0.7091]])

In [16]:
# 튜플
torch.rand((2, 3))

tensor([[0.7467, 0.4716, 0.5293],
        [0.4915, 0.8716, 0.9973]])

In [18]:
torch.randn(2, 3)

tensor([[ 0.0159,  0.8213, -0.1489],
        [-0.3494,  1.6332,  1.1701]])

파이썬 리스트 data_list와 NumPy array data_np가 주어져 있습니다. 이 두 데이터를 PyTorch 텐서로 만들어 주세요.

data_list에서 만든 텐서는 tensor_from_list 변수에 저장하고, data_np에서 만든 텐서는 tensor_from_np_array에 저장해야 합니다.



In [19]:
import numpy as np
import torch

data_list = [
    [1, 1],
    [-1, -1],
]

data_np = np.array(
    [
        [3, 4],
        [5,6]
    ]
)

tensor_from_list = torch.tensor(data_list)

tensor_from_np_array = torch.from_numpy(data_np)

print(tensor_from_list)
print(tensor_from_np_array)

tensor([[ 1,  1],
        [-1, -1]])
tensor([[3, 4],
        [5, 6]])
